// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpkguoquonnyemqhmfqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwa2d1b3F1b25ueWVtcWhtZnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODM3NzIsImV4cCI6MjA2MDg1OTc3Mn0.LUbRtaJTPN5ud-YiEYS7SpkmKUFbJVEdu3hFhO2jY6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);